name: Generate Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: git clone https://codeberg.org/aerphanas/kompor.git
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.6.1'
        cabal-version: '3.10.1.0'

    - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Update Package list
      run: cd kompor; cabal update

    - name: Build & Generate
      run: cd kompor; cabal run -- kompor build

    - name: Deploy
      uses: fireaz/push-git-subdirectory-as-branch@develop
      env:
        REPO: git@codeberg.org:aerphanas/pages.git
        BRANCH: main
        FOLDER: kompor/docs
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        KNOWN_HOSTS_FILE: resources/known_hosts
